# Generated by Django 5.2.6 on 2025-09-22 14:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField()),
                ('qr_code', models.ImageField(blank=True, help_text='QR Code gerado automaticamente', upload_to='qrcodes/')),
                ('disponivel', models.BooleanField(default=True)),
                ('codigo_exemplar', models.CharField(help_text='Código único do exemplar', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
                'ordering': ['titulo__titulo_da_obra', 'codigo_exemplar'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lombada', models.CharField(max_length=50, unique=True)),
                ('autor', models.CharField(max_length=200)),
                ('titulo_da_obra', models.CharField(max_length=300)),
                ('titulo_original', models.CharField(blank=True, max_length=300)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('edicao', models.CharField(blank=True, max_length=50)),
                ('editora', models.CharField(max_length=200)),
                ('ano_publicacao', models.IntegerField()),
                ('local_publicacao', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{1,5}-\\d{1,7}-\\d{1,7}-\\d{1}$|^\\d{10}$|^\\d{13}$', 'ISBN inválido')])),
                ('cdu', models.CharField(blank=True, help_text='Classificação Decimal Universal', max_length=50)),
                ('cutter', models.CharField(blank=True, help_text='Número de Cutter', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['titulo_da_obra'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(help_text='Formato: +5511999999999', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de telefone inválido.')])),
                ('dre', models.CharField(help_text='Matrícula/Registro do aluno', max_length=20, unique=True)),
                ('is_administrador', models.BooleanField(default=False, help_text='Designa se o usuário tem privilégios de administrador')),
                ('data_suspensao', models.DateField(blank=True, help_text='Data até quando o usuário está suspenso', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('previsao_devolucao', models.DateField()),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='biblioteca.exemplar')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovacoes', models.IntegerField(default=0)),
                ('notificacoes_enviadas', models.IntegerField(default=0)),
                ('ultima_notificacao', models.DateTimeField(blank=True, null=True)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='biblioteca.emprestimo')),
            ],
            options={
                'verbose_name': 'Histórico de Empréstimo',
                'verbose_name_plural': 'Históricos de Empréstimos',
            },
        ),
        migrations.AddField(
            model_name='exemplar',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='biblioteca.titulo'),
        ),
    ]
