# Generated by Django 5.2.6 on 2025-10-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica se o email foi verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_ativacao',
            field=models.CharField(blank=True, help_text='Token para ativação da conta', max_length=100, null=True),
        ),
    ]
