# Generated by Django 5.2.8 on 2025-11-08 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_usuario_email_verificado_usuario_token_ativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
